import { PrismaClient, TipAngajat, StatusGeneral } from '@prisma/client';

export async function seedAngajati(prisma: PrismaClient) {
  console.log('👨‍🔧 Populăm angajații...');
  await prisma.angajat.createMany({
    data: [
      {
        nume: 'Ionescu',
        prenume: 'Mihai',
        CNP: '1820101223344',
        telefon: '0721 100 201',
        email: 'mihai.ionescu@serviceautog.ro',
        tipAngajat: TipAngajat.Mecanic,
        specializare: 'Mecanică generală',
        costOrar: 170,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Popa',
        prenume: 'Andrei',
        CNP: '1840615223344',
        telefon: '0721 100 202',
        email: 'andrei.popa@serviceautog.ro',
        tipAngajat: TipAngajat.Mecanic,
        specializare: 'Tinichigerie și vopsitorie',
        costOrar: 210,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Marin',
        prenume: 'Elena',
        CNP: '2860226223344',
        telefon: '0721 100 203',
        email: 'elena.marin@serviceautog.ro',
        tipAngajat: TipAngajat.Receptioner,
        nrBirou: 'R-02',
        tura: 'Dimineață',
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Dumitrescu',
        prenume: 'Sorin',
        CNP: '1811111223344',
        telefon: '0721 100 204',
        email: 'sorin.dumitrescu@serviceautog.ro',
        tipAngajat: TipAngajat.Manager,
        departament: 'Operațional',
        sporConducere: 1500,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Neagu',
        prenume: 'Alexandra',
        CNP: '2890305223344',
        telefon: '0721 100 205',
        email: 'alexandra.neagu@serviceautog.ro',
        tipAngajat: TipAngajat.Mecanic,
        specializare: 'Electrică și AC',
        costOrar: 230,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Stoica',
        prenume: 'Lucian',
        CNP: '1791215223344',
        telefon: '0721 100 206',
        email: 'lucian.stoica@serviceautog.ro',
        tipAngajat: TipAngajat.Mecanic,
        specializare: 'Vehicule comerciale și direcție',
        costOrar: 240,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Radu',
        prenume: 'Ioana',
        CNP: '2920707223344',
        telefon: '0721 100 207',
        email: 'ioana.radu@serviceautog.ro',
        tipAngajat: TipAngajat.Receptioner,
        nrBirou: 'R-01',
        tura: 'După-amiază',
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Tănase',
        prenume: 'Cristian',
        CNP: '1770501223344',
        telefon: '0721 100 208',
        email: 'cristian.tanase@serviceautog.ro',
        tipAngajat: TipAngajat.Mecanic,
        specializare: 'Diagnoză electrică avansată',
        costOrar: 260,
        status: StatusGeneral.Activ,
      },
      {
        nume: 'Munteanu',
        prenume: 'Bianca',
        CNP: '2940909223344',
        telefon: '0721 100 209',
        email: 'bianca.munteanu@serviceautog.ro',
        tipAngajat: TipAngajat.Receptioner,
        nrBirou: 'R-03',
        tura: 'Intermediară',
        status: StatusGeneral.Activ,
      },
    ],
  });
  console.log('✅ Angajați inserați.');
}
