import { PrismaClient, TipPiesa } from '@prisma/client';

export async function seedPiese(prisma: PrismaClient) {
  console.log('📦 Populăm piesele...');
  await prisma.piesa.createMany({
    data: [
      {
        codPiesa: 'FIL-UL-BOSCH',
        denumire: 'Filtru Ulei',
        producator: 'Bosch',
        categorie: 'Filtre',
        pretBaza: 45.5,
        stoc: 24,
        tip: TipPiesa.NOUA,
        luniGarantie: 12,
      },
      {
        codPiesa: 'ALT-VW-GOLF',
        denumire: 'Alternator 140A',
        producator: 'Valeo',
        categorie: 'Electrice',
        pretBaza: 350,
        stoc: 0,
        tip: TipPiesa.SH,
        gradUzura: 'Ușor uzat',
      },
      {
        codPiesa: 'PL-FR-RCL',
        denumire: 'Set Plăcuțe Frână Față',
        producator: 'ATE',
        categorie: 'Frânare',
        pretBaza: 265,
        stoc: 5,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'DISC-FR-RCL',
        denumire: 'Disc Frână Ventilat',
        producator: 'Textar',
        categorie: 'Frânare',
        pretBaza: 410,
        stoc: 12,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'COMP-AC-FTR',
        denumire: 'Compresor AC',
        producator: 'Denso',
        categorie: 'Climatizare',
        pretBaza: 1980,
        stoc: 1,
        tip: TipPiesa.SH,
        gradUzura: 'Testat, uzură medie',
      },
      {
        codPiesa: 'BAT-70AH-VAR',
        denumire: 'Baterie 70Ah',
        producator: 'Varta',
        categorie: 'Electrice',
        pretBaza: 540,
        stoc: 8,
        tip: TipPiesa.NOUA,
        luniGarantie: 18,
      },
      {
        codPiesa: 'FIL-AER-MANN',
        denumire: 'Filtru Aer Motor',
        producator: 'MANN',
        categorie: 'Filtre',
        pretBaza: 58,
        stoc: 18,
        tip: TipPiesa.NOUA,
        luniGarantie: 12,
      },
      {
        codPiesa: 'FIL-CAB-HENG',
        denumire: 'Filtru Habitaclu Carbon',
        producator: 'Hengst',
        categorie: 'Filtre',
        pretBaza: 72,
        stoc: 16,
        tip: TipPiesa.NOUA,
        luniGarantie: 12,
      },
      {
        codPiesa: 'AMORT-FATA-SAC',
        denumire: 'Amortizor Față',
        producator: 'Sachs',
        categorie: 'Suspensie & Direcție',
        pretBaza: 385,
        stoc: 7,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'BARA-F-SKO',
        denumire: 'Bară Față Skoda Octavia',
        producator: 'OE Skoda',
        categorie: 'Caroserie',
        pretBaza: 1820,
        stoc: 2,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'FAR-ST-SKO',
        denumire: 'Far Stânga Skoda Octavia',
        producator: 'Hella',
        categorie: 'Electrice',
        pretBaza: 640,
        stoc: 4,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'PARBR-MB-SPR',
        denumire: 'Parbriz Mercedes Sprinter',
        producator: 'Pilkington',
        categorie: 'Caroserie',
        pretBaza: 1280,
        stoc: 1,
        tip: TipPiesa.NOUA,
        luniGarantie: 12,
      },
      {
        codPiesa: 'BASC-MB-SPR',
        denumire: 'Basculă Față Mercedes Sprinter',
        producator: 'Lemforder',
        categorie: 'Suspensie & Direcție',
        pretBaza: 760,
        stoc: 3,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'SET-DIST-VW',
        denumire: 'Kit Distribuție Volkswagen 1.6 TDI',
        producator: 'Contitech',
        categorie: 'Motor',
        pretBaza: 890,
        stoc: 6,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
      {
        codPiesa: 'SEN-PARCARE-OE',
        denumire: 'Senzor Parcare Spate',
        producator: 'Bosch',
        categorie: 'Electrice',
        pretBaza: 220,
        stoc: 9,
        tip: TipPiesa.NOUA,
        luniGarantie: 12,
      },
      {
        codPiesa: 'ANV-IARNA-205',
        denumire: 'Anvelopă Iarnă 205/55 R16',
        producator: 'Michelin',
        categorie: 'Anvelope',
        pretBaza: 430,
        stoc: 20,
        tip: TipPiesa.NOUA,
        luniGarantie: 24,
      },
    ],
  });
  console.log('✅ Piese inserate.');
}
