spring.application.name=proiect
# Configurare baza de date H2 in-memory
spring.datasource.url=jdbc:h2:mem:psidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate va crea tabelele automat pe baza claselor noastre
spring.jpa.hibernate.ddl-auto=update
# Ca sa vedem in consola exact ce SQL genereaza Spring
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Activam consola web a bazei de date (accesibila la http://localhost:8080/h2-console)
spring.h2.console.enabled=true