// Mock data-ul permite rularea completă a modulului fără API.
// În plus, am adăugat clienți și un mic catalog de piese/manoperă pentru un flux
// mai apropiat de recepția reală din service.
// Ideea acestui fișier este simplă:
// - definim câteva entități realiste
// - le legăm între ele prin id-uri
// - pornim aplicația cu un "mic ecosistem" complet funcțional
import { calculeazaRezumatPozitii } from './calculations';
import type {
  Asigurator,
  CatalogKit,
  CatalogManopera,
  CatalogPiesa,
  Client,
  ComandaService,
  DosarDauna,
  Mecanic,
  PozitieComanda,
  Vehicul,
} from './types';

// Clienții sunt separați de vehicule pentru a simula modelul real:
// un client poate avea unul sau mai multe vehicule.
export const mockClienti: Client[] = [
  {
    idClient: 1001,
    nume: 'Ion Popescu',
    telefon: '0722 445 781',
    email: 'ion.popescu@gmail.com',
    tipClient: 'Persoana Fizica',
    denumireCompanie: null,
  },
  {
    idClient: 1002,
    nume: 'Auto Fleet Solutions',
    telefon: '021 440 55 90',
    email: 'service@autofleet.ro',
    tipClient: 'Flota',
    denumireCompanie: 'Auto Fleet Solutions SRL',
  },
  {
    idClient: 1003,
    nume: 'Ana Marinescu',
    telefon: '0744 118 620',
    email: 'ana.marinescu@yahoo.com',
    tipClient: 'Persoana Fizica',
    denumireCompanie: null,
  },
  {
    idClient: 1004,
    nume: 'Tehno Parts Distribution',
    telefon: '031 808 44 12',
    email: 'office@tehnoparts.ro',
    tipClient: 'Persoana Juridica',
    denumireCompanie: 'Tehno Parts Distribution SRL',
  },
  {
    idClient: 1005,
    nume: 'Marius Ilie',
    telefon: '0733 905 118',
    email: 'marius.ilie@gmail.com',
    tipClient: 'Persoana Fizica',
    denumireCompanie: null,
  },
  {
    idClient: 1006,
    nume: 'Urban Courier Fleet',
    telefon: '021 9988 777',
    email: 'operational@urbancourier.ro',
    tipClient: 'Flota',
    denumireCompanie: 'Urban Courier Fleet SA',
  },
];

// Fiecare vehicul indică prin `idClient` cine este proprietarul lui.
export const mockVehicule: Vehicul[] = [
  {
    idVehicul: 1,
    idClient: 1001,
    nrInmatriculare: 'IS-09-SAG',
    marca: 'Dacia',
    model: 'Logan',
    an: 2018,
    serieSasiu: 'UU1LSDL4H60512345',
  },
  {
    idVehicul: 2,
    idClient: 1002,
    nrInmatriculare: 'B-54-GAR',
    marca: 'Skoda',
    model: 'Octavia',
    an: 2021,
    serieSasiu: 'TMBJR7NX1MY102468',
  },
  {
    idVehicul: 3,
    idClient: 1003,
    nrInmatriculare: 'CJ-12-AUT',
    marca: 'Volkswagen',
    model: 'Golf',
    an: 2015,
    serieSasiu: 'WVWZZZAUZFW223344',
  },
  {
    idVehicul: 4,
    idClient: 1004,
    nrInmatriculare: 'B-88-TPD',
    marca: 'Ford',
    model: 'Transit Custom',
    an: 2020,
    serieSasiu: 'WF0YXXTTGYLK55129',
  },
  {
    idVehicul: 5,
    idClient: 1005,
    nrInmatriculare: 'NT-07-MIL',
    marca: 'Renault',
    model: 'Clio',
    an: 2019,
    serieSasiu: 'VF15R980H63218457',
  },
  {
    idVehicul: 6,
    idClient: 1006,
    nrInmatriculare: 'B-412-UCF',
    marca: 'Toyota',
    model: 'Proace City',
    an: 2022,
    serieSasiu: 'YAREFYHZ2GJ118903',
  },
];

export const mockAsiguratori: Asigurator[] = [
  { idAsigurator: 501, denumire: 'Allianz-Tiriac' },
  { idAsigurator: 502, denumire: 'Groupama' },
  { idAsigurator: 503, denumire: 'Omniasig' },
  { idAsigurator: 504, denumire: 'Asirom' },
  { idAsigurator: 505, denumire: 'Generali' },
];

// Mecanicii sunt folosiți în select-ul din formular și în lista de gestiune.
export const mockMecanici: Mecanic[] = [
  { idMecanic: 201, nume: 'Mihai Ionescu', specialitate: 'Mecanica generala' },
  { idMecanic: 202, nume: 'Andrei Popa', specialitate: 'Tinichigerie si vopsitorie' },
  { idMecanic: 203, nume: 'Cristian Pavel', specialitate: 'Diagnoza si electrica' },
  { idMecanic: 204, nume: 'Sorin Dumitrescu', specialitate: 'Mecanica rapida si revizii' },
  { idMecanic: 205, nume: 'Alexandra Neagu', specialitate: 'Aer conditionat si electrica' },
];

// Catalogul de piese oferă sursa din care utilizatorul poate alege rapid articole
// pentru deviz, fără să scrie totul manual.
export const mockCatalogPiese: CatalogPiesa[] = [
  {
    idPiesa: 301,
    cod: 'P-ULEI-5W30',
    denumire: 'Ulei motor 5W30',
    unitateMasura: 'buc',
    pretVanzare: 58,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 302,
    cod: 'P-FIL-U',
    denumire: 'Filtru ulei',
    unitateMasura: 'buc',
    pretVanzare: 95,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 305,
    cod: 'P-BARA-F-SKO',
    denumire: 'Bara față Skoda Octavia',
    unitateMasura: 'buc',
    pretVanzare: 1820,
    cotaTVA: 19,
    disponibilitateStoc: false,
  },
  {
    idPiesa: 306,
    cod: 'P-FAR-ST-SKO',
    denumire: 'Far stânga Skoda Octavia',
    unitateMasura: 'buc',
    pretVanzare: 640,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 307,
    cod: 'P-PL-FR-RCL',
    denumire: 'Plăcuțe frână Renault Clio',
    unitateMasura: 'set',
    pretVanzare: 260,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 308,
    cod: 'P-DISC-FR-RCL',
    denumire: 'Discuri frână față Renault Clio',
    unitateMasura: 'set',
    pretVanzare: 420,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 309,
    cod: 'P-BAT-70AH',
    denumire: 'Acumulator 70Ah',
    unitateMasura: 'buc',
    pretVanzare: 540,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idPiesa: 310,
    cod: 'P-COMP-AC-FTR',
    denumire: 'Compresor AC Ford Transit',
    unitateMasura: 'buc',
    pretVanzare: 2150,
    cotaTVA: 19,
    disponibilitateStoc: false,
  },
];

// Kiturile sunt utile atunci când mai multe materiale sunt vândute ca pachet.
export const mockCatalogKituri: CatalogKit[] = [
  {
    idKit: 701,
    cod: 'K-REV-DAC',
    denumire: 'Kit revizie Dacia Logan',
    unitateMasura: 'kit',
    pretVanzare: 210,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idKit: 702,
    cod: 'K-DISTR-VW',
    denumire: 'Kit distribuție VW 1.6 TDI',
    unitateMasura: 'kit',
    pretVanzare: 1180,
    cotaTVA: 19,
    disponibilitateStoc: false,
  },
  {
    idKit: 703,
    cod: 'K-FR-RCL',
    denumire: 'Kit frânare Renault Clio',
    unitateMasura: 'kit',
    pretVanzare: 640,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
  {
    idKit: 704,
    cod: 'K-AC-FTR',
    denumire: 'Kit service AC Ford Transit',
    unitateMasura: 'kit',
    pretVanzare: 380,
    cotaTVA: 19,
    disponibilitateStoc: true,
  },
];

// Pentru manoperă folosim un catalog separat, deoarece aici vorbim despre tarif/oră,
// nu despre piese fizice aflate sau nu pe stoc.
export const mockCatalogManopera: CatalogManopera[] = [
  {
    idManopera: 401,
    cod: 'M-REV',
    denumire: 'Revizie generală',
    unitateMasura: 'ore',
    tarif: 170,
    cotaTVA: 19,
  },
  {
    idManopera: 402,
    cod: 'M-TIN-VOPS',
    denumire: 'Tinichigerie și vopsitorie element',
    unitateMasura: 'ore',
    tarif: 210,
    cotaTVA: 19,
  },
  {
    idManopera: 403,
    cod: 'M-DIAG',
    denumire: 'Diagnoză computerizată',
    unitateMasura: 'ore',
    tarif: 190,
    cotaTVA: 19,
  },
  {
    idManopera: 404,
    cod: 'M-FR-SCH',
    denumire: 'Înlocuire sistem frânare față',
    unitateMasura: 'ore',
    tarif: 220,
    cotaTVA: 19,
  },
  {
    idManopera: 405,
    cod: 'M-AC',
    denumire: 'Service și diagnoză instalație AC',
    unitateMasura: 'ore',
    tarif: 230,
    cotaTVA: 19,
  },
];

// Dosarele de daună sunt legate atât de client, cât și de vehicul și asigurator.
// Astfel putem simula fluxul în care o comandă de service este susținută de un dosar existent.
export const mockDosareDauna: DosarDauna[] = [
  {
    idDosar: 1,
    idClient: 1002,
    idVehicul: 2,
    idAsigurator: 501,
    nrDosar: 'DAUNA-2026-001',
    numarReferintaAsigurator: 'ALT-CASCO-88214',
    tipPolita: 'CASCO',
    dataDeschidere: new Date('2026-03-14T09:00:00'),
    dataConstatare: new Date('2026-03-15T10:00:00'),
    sumaAprobata: 5200,
    franciza: 600,
    statusAprobare: 'Aprobat partial',
    inspectorDauna: 'Radu Enache',
    observatiiDauna: 'Așteaptă confirmare pentru elementele suplimentare de vopsit.',
  },
  {
    idDosar: 2,
    idClient: 1003,
    idVehicul: 3,
    idAsigurator: 503,
    nrDosar: 'DAUNA-2026-002',
    numarReferintaAsigurator: 'OMN-RCA-99312',
    tipPolita: 'RCA',
    dataDeschidere: new Date('2026-03-18T11:30:00'),
    dataConstatare: new Date('2026-03-18T14:00:00'),
    sumaAprobata: 2800,
    franciza: 300,
    statusAprobare: 'In analiza',
    inspectorDauna: 'Gabriela Oprea',
    observatiiDauna: 'Se verifică devizul inițial transmis de service.',
  },
  {
    idDosar: 3,
    idClient: 1004,
    idVehicul: 4,
    idAsigurator: 504,
    nrDosar: 'DAUNA-2026-003',
    numarReferintaAsigurator: 'ASI-CASCO-77124',
    tipPolita: 'CASCO',
    dataDeschidere: new Date('2026-03-10T08:20:00'),
    dataConstatare: new Date('2026-03-10T13:40:00'),
    sumaAprobata: 4900,
    franciza: 0,
    statusAprobare: 'Aprobat',
    inspectorDauna: 'Valentin Pavel',
    observatiiDauna: 'Înlocuire compresor AC și revizie instalație după avarie internă.',
  },
  {
    idDosar: 4,
    idClient: 1006,
    idVehicul: 6,
    idAsigurator: 502,
    nrDosar: 'DAUNA-2026-004',
    numarReferintaAsigurator: 'GRA-RCA-22481',
    tipPolita: 'RCA',
    dataDeschidere: new Date('2026-03-22T09:10:00'),
    dataConstatare: new Date('2026-03-22T11:30:00'),
    sumaAprobata: 3600,
    franciza: 450,
    statusAprobare: 'Deschis',
    inspectorDauna: 'Irina Moldovan',
    observatiiDauna: 'Vehicul de flotă cu elemente laterale afectate, deviz în analiză.',
  },
];

// Pozițiile sunt grupate pe comandă pentru a păstra mai clar relația
// dintre deviz și comanda în care apare.
const pozitiiComanda1: PozitieComanda[] = [
  {
    idPozitieCmd: 1,
    idComanda: 1,
    idPiesa: 301,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-ULEI-5W30',
    descriere: 'Ulei motor 5W30',
    unitateMasura: 'buc',
    cantitate: 4,
    pretVanzare: 58,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Înlocuire conform planului de întreținere.',
  },
  {
    idPozitieCmd: 2,
    idComanda: 1,
    idPiesa: null,
    idKit: null,
    idManopera: 401,
    tipPozitie: 'Manopera',
    codArticol: 'M-REV',
    descriere: 'Revizie generală',
    unitateMasura: 'ore',
    cantitate: 1.2,
    pretVanzare: 170,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Include verificare filtre și lichide.',
  },
  {
    idPozitieCmd: 3,
    idComanda: 1,
    idPiesa: 302,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-FIL-U',
    descriere: 'Filtru ulei',
    unitateMasura: 'buc',
    cantitate: 1,
    pretVanzare: 95,
    discountProcent: 5,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Promoție fidelizare client.',
  },
];

const pozitiiComanda2: PozitieComanda[] = [
  {
    idPozitieCmd: 4,
    idComanda: 2,
    idPiesa: 305,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-BARA-F-SKO',
    descriere: 'Bara față Skoda Octavia',
    unitateMasura: 'buc',
    cantitate: 1,
    pretVanzare: 1820,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: false,
    observatiiPozitie: 'Piesa comandată, termen estimat 3 zile.',
  },
  {
    idPozitieCmd: 5,
    idComanda: 2,
    idPiesa: 306,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-FAR-ST-SKO',
    descriere: 'Far stânga Skoda Octavia',
    unitateMasura: 'buc',
    cantitate: 1,
    pretVanzare: 640,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Disponibil pe stoc local.',
  },
  {
    idPozitieCmd: 6,
    idComanda: 2,
    idPiesa: null,
    idKit: null,
    idManopera: 402,
    tipPozitie: 'Manopera',
    codArticol: 'M-TIN-VOPS',
    descriere: 'Tinichigerie și vopsitorie element',
    unitateMasura: 'ore',
    cantitate: 6,
    pretVanzare: 210,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Execuție după aprobarea finală a devizului.',
  },
];

const pozitiiComanda3: PozitieComanda[] = [
  {
    idPozitieCmd: 7,
    idComanda: 3,
    idPiesa: null,
    idKit: 702,
    idManopera: null,
    tipPozitie: 'Kit',
    codArticol: 'K-DISTR-VW',
    descriere: 'Kit distribuție VW 1.6 TDI',
    unitateMasura: 'kit',
    cantitate: 1,
    pretVanzare: 1180,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: false,
    observatiiPozitie: 'Kit comandat extern, sosire estimată mâine.',
  },
  {
    idPozitieCmd: 8,
    idComanda: 3,
    idPiesa: null,
    idKit: null,
    idManopera: 403,
    tipPozitie: 'Manopera',
    codArticol: 'M-DIAG',
    descriere: 'Diagnoză computerizată',
    unitateMasura: 'ore',
    cantitate: 1,
    pretVanzare: 190,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Diagnoză completă pentru erori distribuție și injecție.',
  },
];

const pozitiiComanda4: PozitieComanda[] = [
  {
    idPozitieCmd: 9,
    idComanda: 4,
    idPiesa: 307,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-PL-FR-RCL',
    descriere: 'Plăcuțe frână Renault Clio',
    unitateMasura: 'set',
    cantitate: 1,
    pretVanzare: 260,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Piese OEM aprobate de client.',
  },
  {
    idPozitieCmd: 10,
    idComanda: 4,
    idPiesa: 308,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-DISC-FR-RCL',
    descriere: 'Discuri frână față Renault Clio',
    unitateMasura: 'set',
    cantitate: 1,
    pretVanzare: 420,
    discountProcent: 5,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Discount service weekend.',
  },
  {
    idPozitieCmd: 11,
    idComanda: 4,
    idPiesa: null,
    idKit: null,
    idManopera: 404,
    tipPozitie: 'Manopera',
    codArticol: 'M-FR-SCH',
    descriere: 'Înlocuire sistem frânare față',
    unitateMasura: 'ore',
    cantitate: 2,
    pretVanzare: 220,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Probă de drum inclusă.',
  },
];

const pozitiiComanda5: PozitieComanda[] = [
  {
    idPozitieCmd: 12,
    idComanda: 5,
    idPiesa: 309,
    idKit: null,
    idManopera: null,
    tipPozitie: 'Piesa',
    codArticol: 'P-BAT-70AH',
    descriere: 'Acumulator 70Ah',
    unitateMasura: 'buc',
    cantitate: 1,
    pretVanzare: 540,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Înlocuire baterie veche cu capacitate echivalentă.',
  },
  {
    idPozitieCmd: 13,
    idComanda: 5,
    idPiesa: null,
    idKit: 704,
    idManopera: null,
    tipPozitie: 'Kit',
    codArticol: 'K-AC-FTR',
    descriere: 'Kit service AC Ford Transit',
    unitateMasura: 'kit',
    cantitate: 1,
    pretVanzare: 380,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Filtre și consumabile pentru intervenția AC.',
  },
  {
    idPozitieCmd: 14,
    idComanda: 5,
    idPiesa: null,
    idKit: null,
    idManopera: 405,
    tipPozitie: 'Manopera',
    codArticol: 'M-AC',
    descriere: 'Service și diagnoză instalație AC',
    unitateMasura: 'ore',
    cantitate: 2.5,
    pretVanzare: 230,
    discountProcent: 0,
    cotaTVA: 19,
    disponibilitateStoc: true,
    observatiiPozitie: 'Lucrare finalizată după înlocuirea compresorului.',
  },
];

// Lista generală de poziții este construită prin concatenarea tuturor grupurilor.
export const mockPozitii: PozitieComanda[] = [
  ...pozitiiComanda1,
  ...pozitiiComanda2,
  ...pozitiiComanda3,
  ...pozitiiComanda4,
  ...pozitiiComanda5,
];

// Totalul estimat al fiecărei comenzi este calculat din pozițiile ei.
// Așa ne asigurăm că datele de demo sunt coerente cu formula folosită în UI.
export const mockComenzi: ComandaService[] = [
  {
    idComanda: 1,
    idVehicul: 1,
    idDosar: null,
    idMecanic: 201,
    nrComanda: 'CMD-2026-001',
    dataDeschidere: new Date('2026-03-19T08:30:00'),
    dataFinalizare: null,
    status: 'Asteapta aprobare client',
    totalEstimat: calculeazaRezumatPozitii(pozitiiComanda1).total,
    kilometrajPreluare: 146220,
    nivelCombustibil: '1/2',
    simptomeReclamate: 'Revizie anuală și zgomot ușor la frânare pe față.',
    observatiiPreluare: 'Clientul solicită confirmare telefonică înainte de lucrări suplimentare.',
    observatiiCaroserie: 'Zgârieturi fine pe bara spate, fără legătură cu intervenția.',
    accesoriiPredate: ['Talonaș', 'Cheie principală', 'Roată de rezervă'],
    termenPromis: new Date('2026-03-27T17:30:00'),
    prioritate: 'Normala',
    tipPlata: 'Client Direct',
  },
  {
    idComanda: 2,
    idVehicul: 2,
    idDosar: 1,
    idMecanic: 202,
    nrComanda: 'CMD-2026-002',
    dataDeschidere: new Date('2026-03-20T10:15:00'),
    dataFinalizare: null,
    status: 'Asteapta piese',
    totalEstimat: calculeazaRezumatPozitii(pozitiiComanda2).total,
    kilometrajPreluare: 84210,
    nivelCombustibil: '3/4',
    simptomeReclamate: 'Elemente avariate în partea frontală după incident minor.',
    observatiiPreluare: 'Vehicul de flotă, reprezentantul firmei aprobă devizul pe email.',
    observatiiCaroserie: 'Capotă ușor dezaliniată, stropitoare parbriz fisurată.',
    accesoriiPredate: ['Carte service', 'Cheie principală', 'Laptop diagnoză flotă'],
    termenPromis: new Date('2026-03-28T16:00:00'),
    prioritate: 'Ridicata',
    tipPlata: 'Asigurare',
  },
  {
    idComanda: 3,
    idVehicul: 3,
    idDosar: 2,
    idMecanic: 203,
    nrComanda: 'CMD-2026-003',
    dataDeschidere: new Date('2026-03-21T09:40:00'),
    dataFinalizare: null,
    status: 'In Lucru',
    totalEstimat: calculeazaRezumatPozitii(pozitiiComanda3).total,
    kilometrajPreluare: 188540,
    nivelCombustibil: '1/4',
    simptomeReclamate: 'Motorul pornește greu și apar erori intermitente la distribuție.',
    observatiiPreluare: 'Clientul dorește păstrarea pieselor înlocuite pentru verificare.',
    observatiiCaroserie: 'Portiera stânga spate prezintă o lovitură veche, fără legătură cu intervenția.',
    accesoriiPredate: ['Talonaș', 'Cheie principală'],
    termenPromis: new Date('2026-03-29T15:00:00'),
    prioritate: 'Normala',
    tipPlata: 'Asigurare',
  },
  {
    idComanda: 4,
    idVehicul: 5,
    idDosar: null,
    idMecanic: 204,
    nrComanda: 'CMD-2026-004',
    dataDeschidere: new Date('2026-03-17T08:50:00'),
    dataFinalizare: null,
    status: 'Gata de livrare',
    totalEstimat: calculeazaRezumatPozitii(pozitiiComanda4).total,
    kilometrajPreluare: 97310,
    nivelCombustibil: '1/2',
    simptomeReclamate: 'Vibrații la frânare și zgomot metalic pe puntea față.',
    observatiiPreluare: 'Clientul revine la finalul programului pentru ridicare.',
    observatiiCaroserie: 'Fără observații vizibile la preluare.',
    accesoriiPredate: ['Cheie principală', 'Triunghi reflectorizant'],
    termenPromis: new Date('2026-03-24T18:00:00'),
    prioritate: 'Ridicata',
    tipPlata: 'Client Direct',
  },
  {
    idComanda: 5,
    idVehicul: 4,
    idDosar: 3,
    idMecanic: 205,
    nrComanda: 'CMD-2026-005',
    dataDeschidere: new Date('2026-03-12T10:00:00'),
    dataFinalizare: new Date('2026-03-23T14:30:00'),
    status: 'Livrat',
    totalEstimat: calculeazaRezumatPozitii(pozitiiComanda5).total,
    kilometrajPreluare: 121430,
    nivelCombustibil: '3/4',
    simptomeReclamate: 'Instalația AC nu mai răcește, iar bateria se descarcă rapid.',
    observatiiPreluare: 'Vehicul comercial; aprobarea s-a făcut prin managerul de flotă.',
    observatiiCaroserie: 'Urme minore de exploatare pe laterala dreaptă.',
    accesoriiPredate: ['Cheie principală', 'Card flotă combustibil'],
    termenPromis: new Date('2026-03-23T17:00:00'),
    prioritate: 'Urgenta',
    tipPlata: 'Asigurare',
  },
];
